[project]
name = "solr-reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.12.4",
    "openai>=1.99.9",
    "together>=1.5.23",
]
